name: CI/CD Pipeline

on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports: 
          - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup docker BuildX
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Account
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Test Backend
        run: | 
          cd backend
          docker build -t alildb/backend .
          docker tag alildb/backend alildb/backend:latest
          docker push alildb/backend:latest
      - name: Build Test Frontend
        run: |
          cd smartneighbors
          docker build -t alildb/smartneighbors .
          docker tag alildb/backend alildb/smartneighbors:latest
          docker push alildb/smartneighbors:latest
      - name: Deploy to AWS 
        run: |
         # AWS Deployment scripts
          
      
      
