name: CI/CD Pipeline

on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports: 
          - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup docker BuildX
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Account
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      
